### ISSUE TITLE
Broke on >= RN36

### ISSUE THREAD

**Issue by sibelius** [sbycrosz/react-native-credit-card-input#14]
https://github.com/sonnylazuardi/react-native-credit-card/issues/7

**Comment by sibelius** [comment]
this PR fixes this problem: https://github.com/sonnylazuardi/react-native-credit-card/pull/6

**Comment by sibelius** [comment]
@sbycrosz can u upgrade react-native-credit-card ? 

the PR https://github.com/sonnylazuardi/react-native-credit-card/pull/6 was fixed

**Comment by sbycrosz** [comment]
Done!
Thanks @sibelius

**Comment by ssomnoremac** [comment]
this is still broken on 0.2.8 on iOS. The Lite form I can't see the input. The regular form the Card image doesn't render.

**Comment by sbycrosz** [comment]
It seems RN0.37+ broke the existing `{ flex: 1 }` styles.
I fixed the LiteCreditCardInput for now & I'll try to update this lib by the weekend ;)

**Comment by sbycrosz** [comment]
Should be fixed @latest
