### ISSUE TITLE
Getting a Warning KeyboardShouldPersistTaps={true} is deprecated 

### ISSUE THREAD

**Issue by ntk860** [sbycrosz/react-native-credit-card-input#59]
It is suggesting to use KeyboardShouldPersistTaps="always". Can you change it please ?

**Comment by eeynard** [comment]
Fixed in https://github.com/sbycrosz/react-native-credit-card-input/commit/a45f291641ba84c5d30076da5aa1229a855a5726

**Comment by ntk860** [comment]
thank you

**Comment by chapeljuice** [comment]
This did not fix it for me. I'm still getting that same error. Any thoughts?
